spring.application.name=Authentication-Service

server.port=8081
db-service.base-url=${DB_SERVICE_BASE_URL:http://db-service:8082}
jwt.secret=${JWT_SECRET:256-bit-secret-for-petquest-idp}
jwt.access-token-expiry=${JWT_ACCESS_TOKEN_EXPIRY:900000}
jwt.refresh-token-expiry=${JWT_REFRESH_TOKEN_EXPIRY:2592000000}
